### ISSUE TITLE
Some places confused me in `options.py`

### ISSUE THREAD

**Issue by CiaoHe** [ahangchen/torch_base#2]
Hi there!

https://github.com/ahangchen/torch_base/blob/a57aab445e27546df3e48579e1ebbf02bfb7db61/options.py#L63-L64
According to these two lines, if we set arguments as default, `(load_model_path='checkpoints/base_model_pref/0.pth', save_prefix='pref', val_list='/data/dataset1/list/base/val.txt')`, 

then the `result_dir` shows like  `checkpoints/base_model_pref/.pth/base_val_pref`.

I wonder if there are any mistakes or do you just want to save test results under the `.pth` folder?

Thanks for your contribution~

**Comment by ahangchen** [comment]
It's a mistake. 
`ext` should be the last slice of split.
Thank you for your review. I have fixed it.
